// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sundown2._0.Data;

namespace Sundown2._0.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220929085701_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Sundown2._0.Entities.Astronaut", b =>
                {
                    b.Property<Guid>("AstronautId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AstronautId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.ToTable("Astronauts");

                    b.HasData(
                        new
                        {
                            AstronautId = new Guid("d209ab46-a03b-47d7-a4b6-348c62f7e18a"),
                            Avatar = "C:\\Users\\balde\\source\\repos\\Sundown2.0\\Sundown2.0\\Media\\Images\\Yuga.jpg",
                            CodeName = "First Man",
                            Email = "yuga@mtr.moon",
                            FirstName = "Yuri",
                            LastName = "Gagarin",
                            Password = "ucJa3b1m3QCZvHM67PqYNTjKrqm6xJ01C/cXXSlvcRM=:eNJJotJygM5lfRT7VsnM5w==",
                            Username = "yuga"
                        },
                        new
                        {
                            AstronautId = new Guid("fad20788-1ebd-4ce6-a133-42eb34237d15"),
                            Avatar = "C:\\Users\\balde\\source\\repos\\Sundown2.0\\Sundown2.0\\Media\\Images\\Alsh.jpg",
                            CodeName = "Shepard",
                            Email = "alsh@mtr.moon",
                            FirstName = "Alan",
                            LastName = "Shepard",
                            Password = "ITzi4V0MySnXMJA5WJu+p/zrjJ7v8F6JR//bUq7kzTM=:54+4rtMAB8384oiNiNCTDg==",
                            Username = "alsh"
                        },
                        new
                        {
                            AstronautId = new Guid("f4b917ea-9102-41cc-9a11-eed91af2119b"),
                            Avatar = "C:\\Users\\balde\\source\\repos\\Sundown2.0\\Sundown2.0\\Media\\Images\\Vate.jpg",
                            CodeName = "Valentine",
                            Email = "vate@mtr.moon",
                            FirstName = "Valentina",
                            LastName = "Tereshkova",
                            Password = "F0RxBSmnVern/V/fHx4SNRMeZ+G6y/weNcBI37ONaSg=:/7FYNPQaAzjB+Qv7oTaXVw==",
                            Username = "vate"
                        },
                        new
                        {
                            AstronautId = new Guid("de7ae37e-a55c-42f4-8a54-d6df16488710"),
                            Avatar = "C:\\Users\\balde\\source\repos\\Sundown2.0\\Sundown2.0\\Media\\Images\\Gubl.jpg",
                            CodeName = "bluey",
                            Email = "gubi@mtr.moon",
                            FirstName = "Guion",
                            LastName = "Bluford",
                            Password = "VHblRfxl4dZ2pPNtHWih3gAWtQKtRwa4rtvctzafJPo=:/mo5k7OFhrEkp6m+z0PNsA==",
                            Username = "gubl"
                        },
                        new
                        {
                            AstronautId = new Guid("527b65e7-35f6-4f1f-adab-0a6233091a19"),
                            Avatar = "C:\\Users\\balde\\source\\repos\\Sundown2.0\\Sundown2.0\\Media\\Images\\Anmo.jpg",
                            CodeName = "Great Dane",
                            Email = "anmo@mtr.moon",
                            FirstName = "Andreas",
                            LastName = "Mogensen",
                            Password = "K2HIUcKqjvNUUoHSWczlnnSnR4s6gWZ1F4sqGexWQGI=:mlopqmOCKizStvRG3z14PQ==",
                            Username = "anmo"
                        },
                        new
                        {
                            AstronautId = new Guid("b1c9bcfb-ac17-42db-924d-062c755aa474"),
                            Avatar = "C:\\Users\\balde\\source\\repos\\Sundown2.0\\Sundown2.0\\Media\\Images\\Yiso.jpeg",
                            CodeName = "Neon",
                            Email = "yiso@mtr.moon",
                            FirstName = "Yi",
                            LastName = "So-Yeon",
                            Password = "zygdXJKeXaglxCmRv3uF7c7Jhn/KMEIhSdEZqwJRRow=:sdRQ1lQmTJ+3F8N0jnSUCQ==",
                            Username = "yiso"
                        });
                });

            modelBuilder.Entity("Sundown2._0.Entities.ClosestLandingFacility", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CountryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("CurrentDistanceInMeters")
                        .HasColumnType("float");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ClosestLandingFacility");
                });

            modelBuilder.Entity("Sundown2._0.Entities.LandingFacility", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("DistanceToISS")
                        .HasColumnType("float");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("LandingFacilities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DistanceToISS = 0.0,
                            Latitude = 55.684740222145393,
                            Longitude = 12.509714835254639,
                            Name = "Europe"
                        },
                        new
                        {
                            Id = 2,
                            DistanceToISS = 0.0,
                            Latitude = 41.149626026644633,
                            Longitude = 119.33727554032843,
                            Name = "China"
                        },
                        new
                        {
                            Id = 3,
                            DistanceToISS = 0.0,
                            Latitude = 40.014407426017335,
                            Longitude = -103.68329704730307,
                            Name = "America"
                        },
                        new
                        {
                            Id = 4,
                            DistanceToISS = 0.0,
                            Latitude = -21.029736672213531,
                            Longitude = 23.770767883255459,
                            Name = "Africa"
                        },
                        new
                        {
                            Id = 5,
                            DistanceToISS = 0.0,
                            Latitude = -33.007020987324388,
                            Longitude = 117.83314818861444,
                            Name = "Australia"
                        },
                        new
                        {
                            Id = 6,
                            DistanceToISS = 0.0,
                            Latitude = 19.330540162912126,
                            Longitude = 79.14236662251713,
                            Name = "India"
                        },
                        new
                        {
                            Id = 7,
                            DistanceToISS = 0.0,
                            Latitude = -34.050351176517886,
                            Longitude = -65.926829655687428,
                            Name = "Argentina"
                        });
                });

            modelBuilder.Entity("Sundown2._0.Entities.MissionImage", b =>
                {
                    b.Property<Guid>("MissionImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CameraName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("MissionReportId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RoverName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoverStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("MissionImageId");

                    b.HasIndex("MissionReportId");

                    b.ToTable("MissionImages");
                });

            modelBuilder.Entity("Sundown2._0.Entities.MissionReport", b =>
                {
                    b.Property<Guid>("MissionReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AstronautId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FinalisationDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<DateTime>("MissionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("MissionReportId");

                    b.HasIndex("AstronautId");

                    b.ToTable("MissionReports");
                });

            modelBuilder.Entity("Sundown2._0.Entities.MissionImage", b =>
                {
                    b.HasOne("Sundown2._0.Entities.MissionReport", null)
                        .WithMany("MissionImages")
                        .HasForeignKey("MissionReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sundown2._0.Entities.MissionReport", b =>
                {
                    b.HasOne("Sundown2._0.Entities.Astronaut", "Astronaut")
                        .WithMany("MissionReports")
                        .HasForeignKey("AstronautId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Astronaut");
                });

            modelBuilder.Entity("Sundown2._0.Entities.Astronaut", b =>
                {
                    b.Navigation("MissionReports");
                });

            modelBuilder.Entity("Sundown2._0.Entities.MissionReport", b =>
                {
                    b.Navigation("MissionImages");
                });
#pragma warning restore 612, 618
        }
    }
}
