// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sundown2._0.Data;

namespace Sundown2._0.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220929095337_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Sundown2._0.Entities.Astronaut", b =>
                {
                    b.Property<Guid>("AstronautId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AstronautId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.ToTable("Astronauts");

                    b.HasData(
                        new
                        {
                            AstronautId = new Guid("8c0e2924-e290-4cd3-a7eb-d360a6a51fbc"),
                            Avatar = "C:\\Users\\balde\\source\\repos\\Sundown2.0\\Sundown2.0\\Media\\Images\\Yuga.jpg",
                            CodeName = "First Man",
                            Email = "yuga@mtr.moon",
                            FirstName = "Yuri",
                            LastName = "Gagarin",
                            Password = "ucJa3b1m3QCZvHM67PqYNTjKrqm6xJ01C/cXXSlvcRM=:eNJJotJygM5lfRT7VsnM5w==",
                            Username = "yuga"
                        },
                        new
                        {
                            AstronautId = new Guid("3be03faa-9c78-4d3b-bc08-8c3c89bac208"),
                            Avatar = "C:\\Users\\balde\\source\\repos\\Sundown2.0\\Sundown2.0\\Media\\Images\\Alsh.jpg",
                            CodeName = "Shepard",
                            Email = "alsh@mtr.moon",
                            FirstName = "Alan",
                            LastName = "Shepard",
                            Password = "ITzi4V0MySnXMJA5WJu+p/zrjJ7v8F6JR//bUq7kzTM=:54+4rtMAB8384oiNiNCTDg==",
                            Username = "alsh"
                        },
                        new
                        {
                            AstronautId = new Guid("9e70fddc-0693-4c38-be13-3f6a9681f2ec"),
                            Avatar = "C:\\Users\\balde\\source\\repos\\Sundown2.0\\Sundown2.0\\Media\\Images\\Vate.jpg",
                            CodeName = "Valentine",
                            Email = "vate@mtr.moon",
                            FirstName = "Valentina",
                            LastName = "Tereshkova",
                            Password = "F0RxBSmnVern/V/fHx4SNRMeZ+G6y/weNcBI37ONaSg=:/7FYNPQaAzjB+Qv7oTaXVw==",
                            Username = "vate"
                        },
                        new
                        {
                            AstronautId = new Guid("c37140b0-fd12-4867-9868-03f82ccba040"),
                            Avatar = "C:\\Users\\balde\\source\repos\\Sundown2.0\\Sundown2.0\\Media\\Images\\Gubl.jpg",
                            CodeName = "bluey",
                            Email = "gubi@mtr.moon",
                            FirstName = "Guion",
                            LastName = "Bluford",
                            Password = "VHblRfxl4dZ2pPNtHWih3gAWtQKtRwa4rtvctzafJPo=:/mo5k7OFhrEkp6m+z0PNsA==",
                            Username = "gubl"
                        },
                        new
                        {
                            AstronautId = new Guid("f8928099-a389-467d-93ee-32be7c14f62b"),
                            Avatar = "C:\\Users\\balde\\source\\repos\\Sundown2.0\\Sundown2.0\\Media\\Images\\Anmo.jpg",
                            CodeName = "Great Dane",
                            Email = "anmo@mtr.moon",
                            FirstName = "Andreas",
                            LastName = "Mogensen",
                            Password = "K2HIUcKqjvNUUoHSWczlnnSnR4s6gWZ1F4sqGexWQGI=:mlopqmOCKizStvRG3z14PQ==",
                            Username = "anmo"
                        },
                        new
                        {
                            AstronautId = new Guid("95cef011-8395-4876-a8dc-b3d542137d6d"),
                            Avatar = "C:\\Users\\balde\\source\\repos\\Sundown2.0\\Sundown2.0\\Media\\Images\\Yiso.jpeg",
                            CodeName = "Neon",
                            Email = "yiso@mtr.moon",
                            FirstName = "Yi",
                            LastName = "So-Yeon",
                            Password = "zygdXJKeXaglxCmRv3uF7c7Jhn/KMEIhSdEZqwJRRow=:sdRQ1lQmTJ+3F8N0jnSUCQ==",
                            Username = "yiso"
                        });
                });

            modelBuilder.Entity("Sundown2._0.Entities.ClosestLandingFacility", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CountryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("CurrentDistanceInMeters")
                        .HasColumnType("float");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ClosestLandingFacility");
                });

            modelBuilder.Entity("Sundown2._0.Entities.LandingFacility", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("DistanceToISS")
                        .HasColumnType("float");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("LandingFacilities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e378f454-0793-46e6-824c-2e8aae7190bb"),
                            DistanceToISS = 0.0,
                            Latitude = 55.684740222145393,
                            Longitude = 12.509714835254639,
                            Name = "Europe"
                        },
                        new
                        {
                            Id = new Guid("f090f415-9d6d-45c6-8b83-9ccb77d6e114"),
                            DistanceToISS = 0.0,
                            Latitude = 41.149626026644633,
                            Longitude = 119.33727554032843,
                            Name = "China"
                        },
                        new
                        {
                            Id = new Guid("25e4a43b-7e7e-423c-982b-f01017547f5d"),
                            DistanceToISS = 0.0,
                            Latitude = 40.014407426017335,
                            Longitude = -103.68329704730307,
                            Name = "America"
                        },
                        new
                        {
                            Id = new Guid("970a3da5-99a8-48ee-b7ac-06844a5616d0"),
                            DistanceToISS = 0.0,
                            Latitude = -21.029736672213531,
                            Longitude = 23.770767883255459,
                            Name = "Africa"
                        },
                        new
                        {
                            Id = new Guid("c3085e3f-8797-4256-8aaa-7d541726fcd0"),
                            DistanceToISS = 0.0,
                            Latitude = -33.007020987324388,
                            Longitude = 117.83314818861444,
                            Name = "Australia"
                        },
                        new
                        {
                            Id = new Guid("fe78d56f-3413-4196-a532-46910fb297ef"),
                            DistanceToISS = 0.0,
                            Latitude = 19.330540162912126,
                            Longitude = 79.14236662251713,
                            Name = "India"
                        },
                        new
                        {
                            Id = new Guid("69fd5693-2ff6-4f5c-92bc-5c728f1920fe"),
                            DistanceToISS = 0.0,
                            Latitude = -34.050351176517886,
                            Longitude = -65.926829655687428,
                            Name = "Argentina"
                        });
                });

            modelBuilder.Entity("Sundown2._0.Entities.MissionImage", b =>
                {
                    b.Property<Guid>("MissionImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CameraName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("MissionReportId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RoverName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoverStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("MissionImageId");

                    b.HasIndex("MissionReportId");

                    b.ToTable("MissionImages");
                });

            modelBuilder.Entity("Sundown2._0.Entities.MissionReport", b =>
                {
                    b.Property<Guid>("MissionReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AstronautId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FinalisationDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<DateTime>("MissionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("MissionReportId");

                    b.HasIndex("AstronautId");

                    b.ToTable("MissionReports");
                });

            modelBuilder.Entity("Sundown2._0.Entities.MissionImage", b =>
                {
                    b.HasOne("Sundown2._0.Entities.MissionReport", null)
                        .WithMany("MissionImages")
                        .HasForeignKey("MissionReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sundown2._0.Entities.MissionReport", b =>
                {
                    b.HasOne("Sundown2._0.Entities.Astronaut", "Astronaut")
                        .WithMany("MissionReports")
                        .HasForeignKey("AstronautId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Astronaut");
                });

            modelBuilder.Entity("Sundown2._0.Entities.Astronaut", b =>
                {
                    b.Navigation("MissionReports");
                });

            modelBuilder.Entity("Sundown2._0.Entities.MissionReport", b =>
                {
                    b.Navigation("MissionImages");
                });
#pragma warning restore 612, 618
        }
    }
}
